spring.datasource.url=jdbc:postgresql://172.16.1.100:5432/hmsdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# MinIO Server Configuration
minio.url=http://172.16.1.100:9000 
minio.accessKey=minioadmin        
minio.secretKey=minioadmin          
minio.bucketName=infospokejobapplicationsbucket 

# India SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply@infospoke.in
spring.mail.password=Infospoke@123
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.default-encoding=UTF-8


# Kafka
spring.kafka.bootstrap-servers=172.16.1.100:9094
spring.kafka.consumer.group-id=hms-notification-group

# Helps avoid deserialization issues
spring.kafka.consumer.properties.spring.json.value.default.type=com.hms.service.dto.NotificationEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Topic
hms.kafka.notification-topic=hms-notification-topic
# Mail sender (used in NotificationServiceImpl)
hms.mail.from=noreply@infospoke.in

company.name=Infospoke Integrated Solutions LLP
company.email=noreply@infospoke.in
resume.reupload.days=3


