CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS role_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS module_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS permission_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS assign_role_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS sr_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS candidate_id_seq START WITH 1 INCREMENT BY 1;



