DROP TABLE IF EXISTS public.tb_user_type_test;

CREATE TABLE IF NOT EXISTS public.tb_user_type_test
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_type character varying(255) COLLATE pg_catalog."default",
    user_type_id integer,
    CONSTRAINT tb_user_type_pkey PRIMARY KEY (id),
    CONSTRAINT ukfobjxwlvrl4l2u6l72h4s8ogd UNIQUE (user_type_id)
);








